### ISSUE TITLE
Update converter for Flat UI Pro v1.3.2 and greater

### ISSUE THREAD

**Issue by wingrunr21** [wingrunr21/flat-ui-sass#26]

**Comment by adamico** [comment]
@wingrunr21 just a small line to ask you if you need help with this. I'm not going back to using the official gem so if I can help with the converter upgrade to 1.3.1 pro I'll be glad to.

**Comment by wingrunr21** [comment]
Just need to get some time. I was hoping to tackle it this weekend. There's actually a lot of work to do since bootstrap-sass changed some stuff under the hood as well.

**Comment by adamico** [comment]
Thanks, if you need a hand I'm here.

**Comment by akshatpradhan** [comment]
@wingrunr21 +1 for the conversion!

**Comment by akshatpradhan** [comment]
any update on this? Ticket was opened 2 months ago

**Comment by wingrunr21** [comment]
Working on it. If you feel two months is too long, feel free to submit a PR

**Comment by wingrunr21** [comment]
wip in `2-2-support` branch

**Comment by adamico** [comment]
great! I'll have a look at it and do some bug report. Thanks @wingrunr21 .

**Comment by akshatpradhan** [comment]
@wingrunr21 I checked it out, definitely a WIP but looking good!

**Comment by wingrunr21** [comment]
@adamico please don't report bugs on a WIP branch

**Comment by adamico** [comment]
@wingrunr21 I'll wait until you finish

**Comment by jlc75** [comment]
Hello,

Apparently I have the same problem, but no solution for all this time?

I use Flat-UI-Pro-1.3.2 and bootstrap-sass-3.3.3.

Here is the error:

Processing stylesheets...
  Converting LESS files to Scss:
  Reading shared mixins from mixins.less
/Library/Ruby/Gems/2.0.0/gems/bootstrap-sass-3.3.3/tasks/converter/less_conversion.rb:152:in `bootstrap_less_files': undefined method`get_paths_by_type' for #Converter:0x007f99d2082e88 (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/bootstrap-sass-3.3.3/tasks/converter/less_conversion.rb:54:in `shared_mixins'
        from /Library/Ruby/Gems/2.0.0/gems/bootstrap-sass-3.3.3/tasks/converter/less_conversion.rb:160:in`convert_to_scss'
        from /Library/Ruby/Gems/2.0.0/gems/bootstrap-sass-3.3.3/tasks/converter/less_conversion.rb:46:in `convert_less'
        from /Library/Ruby/Gems/2.0.0/gems/flat-ui-sass-2.1.3/lib/tasks/converter/flat_ui_less_conversion.rb:31:in`block in process_flat_ui_stylesheet_assets!'
        from /Library/Ruby/Gems/2.0.0/gems/flat-ui-sass-2.1.3/lib/tasks/converter/flat_ui_less_conversion.rb:26:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/flat-ui-sass-2.1.3/lib/tasks/converter/flat_ui_less_conversion.rb:26:in`process_flat_ui_stylesheet_assets!'
        from /Library/Ruby/Gems/2.0.0/gems/flat-ui-sass-2.1.3/lib/tasks/converter.rb:71:in `process_flat_ui!'
        from /Library/Ruby/Gems/2.0.0/gems/flat-ui-sass-2.1.3/lib/flat-ui-sass/cli.rb:10:in`start'
        from /Library/Ruby/Gems/2.0.0/gems/flat-ui-sass-2.1.3/bin/fui_convert:9:in `<top (required)>'
        from /usr/bin/fui_convert:23:in`load'
        from /usr/bin/fui_convert:23:in `<main>'

Thank you for your help.

**Comment by akshatpradhan** [comment]
@jlc75 We switched back to Bootstrap. The Core Dev's of Flat UI don't understand that its not just the aesthetics that's important, but the Developer Experience as well. Having to figure out how to integrate Flat UI into a rails application and maintain it is just too much work.

**Comment by wingrunr21** [comment]
@akshatpradhan

Complaining about the Flat UI developer experience here won't get you anywhere. I'm _not_ a core Flat UI dev. I don't even work for Designmodo. I built this project because I wanted a SASS version of Flat UI to use for a client project. It is not supported by Designmodo and I maintain this project on my own accord. I get absolutely nothing from Designmodo for maintaining this.

I pushed my changes up to that branch awhile ago but had other things in my life take priority over finishing. You can see that my [Github contribution level](https://github.com/wingrunr21) has seen a significant decrease over the past few months to correlate this. There's nothing stopping anyone (you included) from finishing the work and submitting a PR. I would ask that instead of making passive-aggressive demands for my unpaid time in this thread, you instead make an attempt to contribute. If you are no longer using this project, please take your negativity elsewhere.

**Comment by wingrunr21** [comment]
@jlc75 My apologies for being unable to finish upgrading the converter thus far. I have placed a TODO for this week to try and get back into this. There are a couple of things ahead of this on my list, but I'm hopeful I will be able to tackle it soon.

**Comment by akshatpradhan** [comment]
@wingrunr21 my comments weren't directed at you. In fact, I think this project of yours should really be developed by @designmodo because they're the ones makes sales. 

Their lack of interest in improving the developer experience has made me switch back to bootstrap and I look forward to someone womping Flat UI with a more aesthetically pleasing AND friendlier developer experience.

**Comment by wingrunr21** [comment]
In that, we are in agreement

**Comment by jlc75** [comment]
I understand, damage, good luck.

**Comment by realadeel** [comment]
Good luck indeed, looking forward to this.

**Comment by wingrunr21** [comment]
Alright everyone, the `2-2-support` branch has a preliminarily working converter. I've converted Flat-UI Free with it and there are no Sass errors on page load. There do appear to be a few stylistic bugs I'm still working to fix.

Next steps will be to make sure Pro converts cleanly and then fix incorrectly converted styles.

**Comment by wingrunr21** [comment]
Pro conversion is in the branch. You _must_ use v1.3.2 or higher as the way the mixins are organized changed in that version.

**Comment by neagle** [comment]
Very delighted to see this. Thanks for all of your work on this project.

**Comment by realadeel** [comment]
Agreed - this is huge and so appreciated.

**Comment by adamico** [comment]
:grinning: thanks a ton for your commitment @wingrunr21!

**Comment by wingrunr21** [comment]
Still working on style fixes. As I essentially have to visually compare styles between the demo pages it takes me a bit. :smile:

**Comment by Orayi** [comment]
Don't know if I'm missing something but I seem to have the same issue mentioned on here:

bundle exec fui_convert
Convert Flat UI from LESS to SASS
   type: flat-ui-pro
  input: C:/Users/Nick/Desktop/flat-ui/flat-ui-sass/flat-ui-pro
 output:
     js: vendor/assets/javascripts/flat-ui-pro
   scss: vendor/assets/stylesheets/flat-ui-pro
  fonts: vendor/assets/fonts/flat-ui-pro
 images: vendor/assets/images/flat-ui-pro
Processing stylesheets...
  Converting LESS files to Scss:
  Reading shared mixins from mixins.less
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bootstrap-sass-3.3.7/tasks/converter/less_conversion.rb:158:in `bootstrap_less_files': undefined method `get_paths_by_type' for #<Converter:0x00000003fec678> (NoMethodError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bootstrap-sass-3.3.7/tasks/converter/less_conversion.rb:55:in `shared_mixins'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bootstrap-sass-3.3.7/tasks/converter/less_conversion.rb:164:in `convert_to_scss'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bootstrap-sass-3.3.7/tasks/converter/less_conversion.rb:47:in `convert_less'
        from C:/Users/Nick/Desktop/flat-ui/flat-ui-sass/lib/tasks/converter/flat_ui_less_conversion.rb:31:in `block in process_flat_ui_stylesheet_assets!'
        from C:/Users/Nick/Desktop/flat-ui/flat-ui-sass/lib/tasks/converter/flat_ui_less_conversion.rb:26:in `each'
        from C:/Users/Nick/Desktop/flat-ui/flat-ui-sass/lib/tasks/converter/flat_ui_less_conversion.rb:26:in `process_flat_ui_stylesheet_assets!'
        from C:/Users/Nick/Desktop/flat-ui/flat-ui-sass/lib/tasks/converter.rb:71:in `process_flat_ui!'
        from C:/Users/Nick/Desktop/flat-ui/flat-ui-sass/lib/flat-ui-sass/cli.rb:10:in `start'
        from C:/Users/Nick/Desktop/flat-ui/flat-ui-sass/bin/fui_convert:9:in `<top (required)>'
        from C:/Ruby23-x64/bin/fui_convert:23:in `load'
        from C:/Ruby23-x64/bin/fui_convert:23:in `<main>'
