### ISSUE TITLE
flat_ui_less_conversion.rb:45:in `insert': no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by patrickespake** [wingrunr21/flat-ui-sass#34]
fui_convert not working.

How can I resolve this?

```
➜  coursify git:(cloud66) ✗ bundle exec fui_convert
Convert Flat UI from LESS to SASS
   type: flat-ui-pro
  input: /Users/patrickespake/Projects/coursify/flat-ui-pro
 output:
     js: vendor/assets/javascripts/flat-ui-pro
   scss: vendor/assets/stylesheets/flat-ui-pro
  fonts: vendor/assets/fonts/flat-ui-pro
 images: vendor/assets/images/flat-ui-pro
Processing stylesheets...
  Converting LESS files to Scss:
  Reading shared mixins from mixins.less
/Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bundler/gems/flat-ui-sass-97b99ebd00a7/lib/tasks/converter/flat_ui_less_conversion.rb:45:in `insert': no implicit conversion from nil to integer (TypeError)
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bundler/gems/flat-ui-sass-97b99ebd00a7/lib/tasks/converter/flat_ui_less_conversion.rb:45:in `block in process_flat_ui_stylesheet_assets!'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bundler/gems/flat-ui-sass-97b99ebd00a7/lib/tasks/converter/flat_ui_less_conversion.rb:26:in `each'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bundler/gems/flat-ui-sass-97b99ebd00a7/lib/tasks/converter/flat_ui_less_conversion.rb:26:in `process_flat_ui_stylesheet_assets!'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bundler/gems/flat-ui-sass-97b99ebd00a7/lib/tasks/converter.rb:71:in `process_flat_ui!'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bundler/gems/flat-ui-sass-97b99ebd00a7/lib/flat-ui-sass/cli.rb:10:in `start'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bundler/gems/flat-ui-sass-97b99ebd00a7/bin/fui_convert:9:in `<top (required)>'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bin/fui_convert:23:in `load'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bin/fui_convert:23:in `<main>'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bin/ruby_executable_hooks:15:in `eval'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wingrunr21** [comment]
What version of Flat UI Pro? I'm guessing v1.3 or greater in which case #26 applies

**Comment by patrickespake** [comment]
2013.07.18 - version 1.1.3

**Comment by wingrunr21** [comment]
The converter was initially written against v1.2. That's the minimum version supported.

**Comment by patrickespake** [comment]
Ok. Thanks :(

**Comment by wingrunr21** [comment]
Sorry. Is 1.1 Bootstrap 2 based? If not, you may be able to tweak the less files to get the converter to run.

**Comment by patrickespake** [comment]
Yes, this version of Flat UI is using Twitter Bootstrap 2.
I am starting to use the gem https://github.com/reflection/designmodo-flatuipro-rails and it solved my problem in this moment.

But the Flat UI Pro for Rails never work well for me, I had a lot of problems in my project.

**Comment by wingrunr21** [comment]
ok. That gem vendors the Flat UI assets but does not convert it to sass. I'm glad it solved your problem though!
